// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 5.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'cloture';

  static const String assets_images_Apple_svg_png = 'assets/images/Apple svg.png';
  static const String cloture$assets_images_Apple_svg_png = 'packages/cloture/assets/images/Apple svg.png';

  static const String assets_images_Facebook___png_0_png = 'assets/images/Facebook - png 0.png';
  static const String cloture$assets_images_Facebook___png_0_png = 'packages/cloture/assets/images/Facebook - png 0.png';

  static const String assets_images_Google___png_0_png = 'assets/images/Google - png 0.png';
  static const String cloture$assets_images_Google___png_0_png = 'packages/cloture/assets/images/Google - png 0.png';

  static const String assets_images_clotoure_logo_png = 'assets/images/clotoure logo.png';
  static const String cloture$assets_images_clotoure_logo_png = 'packages/cloture/assets/images/clotoure logo.png';

  static const String assets_svg_back_arrow_svg = 'assets/svg/back arrow.svg';
  static const String cloture$assets_svg_back_arrow_svg = 'packages/cloture/assets/svg/back arrow.svg';
}
