// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 18.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'cloture';

  static const String assets_images_Apple_svg_png = 'assets/images/Apple svg.png';
  static const String cloture$assets_images_Apple_svg_png = 'packages/cloture/assets/images/Apple svg.png';

  static const String assets_images_Facebook___png_0_png = 'assets/images/Facebook - png 0.png';
  static const String cloture$assets_images_Facebook___png_0_png = 'packages/cloture/assets/images/Facebook - png 0.png';

  static const String assets_images_Google___png_0_png = 'assets/images/Google - png 0.png';
  static const String cloture$assets_images_Google___png_0_png = 'packages/cloture/assets/images/Google - png 0.png';

  static const String assets_images_arrow_down_png = 'assets/images/arrow down.png';
  static const String cloture$assets_images_arrow_down_png = 'packages/cloture/assets/images/arrow down.png';

  static const String assets_images_back_arrow_png = 'assets/images/back arrow.png';
  static const String cloture$assets_images_back_arrow_png = 'packages/cloture/assets/images/back arrow.png';

  static const String assets_images_clotoure_logo_png = 'assets/images/clotoure logo.png';
  static const String cloture$assets_images_clotoure_logo_png = 'packages/cloture/assets/images/clotoure logo.png';

  static const String assets_images_home_png = 'assets/images/home.png';
  static const String cloture$assets_images_home_png = 'packages/cloture/assets/images/home.png';

  static const String assets_images_love_icon_png = 'assets/images/love icon.png';
  static const String cloture$assets_images_love_icon_png = 'packages/cloture/assets/images/love icon.png';

  static const String assets_images_mail_sent_png = 'assets/images/mail sent.png';
  static const String cloture$assets_images_mail_sent_png = 'packages/cloture/assets/images/mail sent.png';

  static const String assets_images_notification_png = 'assets/images/notification.png';
  static const String cloture$assets_images_notification_png = 'packages/cloture/assets/images/notification.png';

  static const String assets_images_order_png = 'assets/images/order.png';
  static const String cloture$assets_images_order_png = 'packages/cloture/assets/images/order.png';

  static const String assets_images_profile_pic_png = 'assets/images/profile pic.png';
  static const String cloture$assets_images_profile_pic_png = 'packages/cloture/assets/images/profile pic.png';

  static const String assets_images_profile_png = 'assets/images/profile.png';
  static const String cloture$assets_images_profile_png = 'packages/cloture/assets/images/profile.png';

  static const String assets_images_search_png = 'assets/images/search.png';
  static const String cloture$assets_images_search_png = 'packages/cloture/assets/images/search.png';

  static const String assets_images_searchnormal1_png = 'assets/images/searchnormal1.png';
  static const String cloture$assets_images_searchnormal1_png = 'packages/cloture/assets/images/searchnormal1.png';

  static const String assets_images_shopping_bag_png = 'assets/images/shopping bag.png';
  static const String cloture$assets_images_shopping_bag_png = 'packages/cloture/assets/images/shopping bag.png';

  static const String assets_svg_back_arrow_svg = 'assets/svg/back arrow.svg';
  static const String cloture$assets_svg_back_arrow_svg = 'packages/cloture/assets/svg/back arrow.svg';

  static const String assets_svg_search_svg = 'assets/svg/search.svg';
  static const String cloture$assets_svg_search_svg = 'packages/cloture/assets/svg/search.svg';
}
